### ISSUE TITLE
Missing properties from `graph.stats`

### ISSUE THREAD

**Issue by progval** [vigna/webgraph-rs#109]
The Rust rewrite of permute removed a bunch of properties from `graph.stats`: https://github.com/vigna/webgraph-big/blob/51f1ebec826397a79c500e8c09e7ae7192015285/src/it/unimi/dsi/big/webgraph/BVGraph.java#L2490-L2520 -> https://github.com/vigna/webgraph-rs/blob/af48d3b8f98b2378ebf50e2ea536947bd60c65d8/src/graphs/bvgraph/comp/flags.rs#L89-L170

Are you planning to re-add them?

**Comment by vigna** [comment]
Yes, but the idea was that of putting them elsewhere rather than in the compression code

**Comment by vigna** [comment]
BTW is there any specific stat you had in mind?

**Comment by progval** [comment]
compratio, bitspernode, and bitsperlink seem to be the only ones we used at any point at SWH

**Comment by vigna** [comment]
Oh wow. We don't do even do those? That's bad—I thought the distribution of gaps or such. That should be easy to fix.

**Comment by vigna** [comment]
It is computed with respect to the information-theoretical lower bound. You can have a look at the Java code.

**Comment by zommiommy** [comment]
Done, I checked that on cnr2000 all the parameters match, the only difference is the number of decimal places; On Java is 3 decimals, in this impl is not truncated so ~15.

Should I also truncate it to 3 decimals?

I also added the `length` field, which contains the length in bits of the compressed graph.
