### ISSUE TITLE
Implement simple iteration

### ISSUE THREAD

**Issue by vigna** [vigna/webgraph-rs#25]
Now we need to call `iter_nodes()`. It would be nice to have to do just `for :`.

**Comment by zommiommy** [comment]
Done for [references to graph](https://github.com/vigna/webgraph-rs/blob/cc7223fa77e413880d1fc4a15624da7d67446d77/src/bvgraph/bvgraph_sequential.rs#L273C26-L273C26)

```rust
impl<'a, CRB> IntoIterator for &'a BVGraphSequential<CRB>
where
    CRB: WebGraphCodesReaderBuilder,
{
    type IntoIter = WebgraphSequentialIter<CRB::Reader<'a>>;
    type Item = <WebgraphSequentialIter<CRB::Reader<'a>> as Iterator>::Item;

    fn into_iter(self) -> Self::IntoIter {
        self.iter_nodes()
    }
}
```

We still have to add the constraint for the `Graph` trait.
