### ISSUE TITLE
Remove unsafe pointer dereference

### ISSUE THREAD

**Issue by vigna** [vigna/webgraph-rs#31]
@progval, if you have any suggestion on how to avoid this horrible pointer dereference we'd like to hear!

https://github.com/vigna/webgraph-rs/blob/95fe4ca96f102f5b267525831a26d26e2c089481/src/utils/coo_to_labelled_graph.rs#L113

The problem here is that the iterator of the successor on a node depends on the merged list of arcs. So we couldn't convince the borrow checker that it is safe to return it. It is possible that it is just that—unsafe, not because of limitations of the borrow checker or missing lifetimes, just because you cannot do this.

An alternative would be inversion of control, that is, either having a graph-writer trait or passing a lambda that given (node, succ) puts it in a writer. At that point all the logic connecting the merging process with the iterator would be in a function.

**Comment by progval** [comment]
It does seem unsafe. You could do something like this:

```
let iter: SortedLabelledSequentialPermutedIterator<...> = ...;
let (node1, adj_list1) = iter.next().unwrap();
let (node2, adj_list2) = iter.next().unwrap();
```

then now `adj_list1` and `adj_list2` can be used to mutate `iter` at the same time.

That's an annoyance I've noted with iterators: `next()` can't return values whose lifetime has to expire before the next call to `next()`. Instead you have to provide something like this:

```
    pub fn next<'b>(&'b mut self) -> Option<(usize, SortedLabelledSequentialPermutedIterator<'a, L, I>)> where 'a: 'b
```

**Comment by vigna** [comment]
Mmmmhhh... maybe `next<'a>`? Or I'm at a loss.

**Comment by vigna** [comment]
But this would mean to have a `WeakIterator` interface with that method. And then we would blanket it for implementation with `Iterator`, I guess (it's just restricting a lifetime) and the graph based on sorted pairs would implement `WeakIterator`, not `Iterator`.

**Comment by vigna** [comment]
Like this?

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4aa818db502fc2df28cf65533d7fb632

**Comment by progval** [comment]
You would have to give the iterator a lifetime stricter than the lifetime of `next()`'s caller. Like this: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3be9edbe08287fb0799f44ccd0e6f19d

(I'm using a reference `&'b u32` to illustrate, but in real life it would be `(usize, SortedLabelledSequentialPermutedIterator<'b, L, I>)`)

**Comment by vigna** [comment]
I see. There's a crate https://github.com/sfackler/streaming-iterator that tries to do that by returning references with lifetimes. The nice thing is that it reimplements a lot of useful methods.

**Comment by progval** [comment]
Good find, thanks. I'm probably going to use it myself in [an unrelated crate](https://docs.rs/orcxx/latest/orcxx/structured_reader/struct.StructuredRowReader.html)

**Comment by vigna** [comment]
It might be a bit overkill for us. We would do something like this tho:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=429253ba6b012c56e5ad82f46b95c5fe

Then iterators would be weak by interface but most implementation wouldn't.

I couldn't avoid 'static on the type—if you have suggestions please fix it :).

**Comment by vigna** [comment]
Actually, I was able to make it work with
```
    type WeakItem<'b> = T::Item where T: 'b;
```
But frankly don't fully understand the consequences.

**Comment by progval** [comment]
`type WeakItem<'b> = T::Item` is strictly stronger than `type WeakItem<'b> = T::Item where T: 'b;`; but Rust wants you to put the latter because it doesn't allow trait implementations to provide stronger guarantees than the trait (even if it could simply discard them)

**Comment by vigna** [comment]
Sometimes when I discuss Rust features I understand how my first-year students feel when I try to teach them programming 😂.

**Comment by zommiommy** [comment]
The implication of using a different trait from Iterator is that we won't have any methods like `map`, `filter`, `zip`, or `for_each`, but we would have to implement them ourselves.

This is my current best-effort implementation:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=93073560864c70f90a2de89e3674b97e

Everything seems to work except the filter function.

```rust
let truth = vec![1, 3, 5].into_iter();

(0..10)
    .enumerate_ref()
    .map_ref(|(i, x)| x + i)
    .zip_ref(truth)
    .for_each_ref(|(x, truth)| {
        println!("{} == {} ?", x, truth);
        assert_eq!(x, truth);
    });
```

Note that I had to add the `_ref` suffix to the functions. Otherwise, we would have had to specify from which trait we want the methods **at every call in our code**.

Moreover, we won't be able to do:
```rust
for (node, succs) in &graph {

}
```
As `ReferenceIterator` does not implement `IntoIterator`, while we could do a blanket implementation that would generate a collision on the types that already implement both Iterator and IntoIterator.

While this is suboptimal, we can just do:
```rust
graph.iter_nodes().for_each_ref(|(node, succs)| {

});
```

**Comment by vigna** [comment]
If that's an issue did you check streaming_iterator? That has a lot of implemented stuff.

I cannot look at the code until Monday so my comments might be weird.

An alternative is to have two iterator methods. iter_nodes and iter_nodes_ref. And ideally one tries to do things with the second one.

**Comment by vigna** [comment]
OMG, surreal, this is still open.
