### ISSUE TITLE
Node iterators with lifetimes

### ISSUE THREAD

**Issue by vigna** [vigna/webgraph-rs#34]
Sequential graphs would benefit from a weaker iterator specification:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9b64b71d0d22c09063e4e1419bf8dd76

In particular, this would make it possible to stop using the unsafe pointer dereference to batches of sorted pairs.

Maybe `next_weak` is not a good name. `next_lt` (lifetime)?

**Comment by zommiommy** [comment]
Before doing it, we should finish discussing in issue #31 the implications of this kind of trait.

**Comment by vigna** [comment]
And, also this is so ancient history...
