### ISSUE TITLE
Tracking issue for LLP porting

### ISSUE THREAD

**Issue by vigna** [vigna/webgraph-rs#44]
This is an issue that tracks problems and progress with the LLP porting.

- The current implementation does not perform the last combination step as it appears to be redundant. Redundancy has been tested on a few graphs but more testing would be good.
- The current implementation does not recombine with the best label after each other label. The reasons for this recombination in the code are not clear, and the effects appear to be negligible. However, this double the recombination time.
- We probably want to save the permutation with ε-serde. We do not want naked binary data around.
- Observing the result ɣ-by-ɣ, the Rust and Java implementations appear to have slightly different behavior for larger or smaller ɣ's: in one case Rust is better, in the other Java is better. It would be a good thing to understand why this happens, and if we can get better for all ɣ's.
- Granularity is presently at the node level. In Java it is at the arc level.

**Comment by zacchiro** [comment]
We have a working LLP now. Is something missing or can we close this one?
