### ISSUE TITLE
The BV graph compressor should save offsets

### ISSUE THREAD

**Issue by vigna** [vigna/webgraph-rs#53]

**Comment by vigna** [comment]
@zommiommy  is this already happening?

**Comment by zommiommy** [comment]
I've implemented it only for sequential compression. The parallel one is yet to be implemented. What's the best approach? Should we create several bitstreams and merge them like we do with the graph or is there a better way?

**Comment by vigna** [comment]
Yes, it's the same. Since it's a cumulative stored by deltas, the important thing is that when concatenating you strip the first zero from every batch except the first.

**Comment by vigna** [comment]
In fact, the responsibility of writing the offsets should be delegated to the Encoder in the current architecture.

**Comment by zommiommy** [comment]
done
