### ISSUE TITLE
Non-static ArcListGraph

### ISSUE THREAD

**Issue by progval** [vigna/webgraph-rs#63]
Currently, ArcListGraph can only be created with `'static` adjacency lists:

https://github.com/vigna/webgraph-rs/blob/5cd97c3af1690f898091dd58a30c9978add3afec/src/graph/arc_list_graph.rs#L19-L27

This means it can't be used with data loaded dynamically†, which is every non-toy use case (as far as i can tell)

What's your plan for this? I don't see a way out, my attempts to change it (either a lifetime parameter to `ArcListGraph` or `Self: '_` bounds) make me end up in lifetime hell.

† There is a way out, though: load data into a `Box`, then [leak](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.leak) it to get a `'static`. Given that in practice I'll always end the process right after I'm done reading the `ArcListGraph`, this would be acceptable.

**Comment by vigna** [comment]
Oh, man. I knew I was too excited about this new LendingIterator and it would have exploded at some point. I didn't fully understand the consequences, I was in burnout after a week of lifetime hell and it was compiling, so...

So, it seems like the "complicated" LendingIterator is in fact not that good.

@zommiommy, thoughts?

**Comment by vigna** [comment]
Wait, but transpose (the utility) uses that and it works. Definitely non-toy. What am I missing?

**Comment by vigna** [comment]
Our plan is to review this later. Please use NodeIterator if you need to transform a list of pairs into a LendingIterator you can pass to extend().

**Comment by progval** [comment]
@zommiommy You added the file to `main` instead of editing it on `havoc`: https://github.com/vigna/webgraph-rs/commit/05d3e3a5b8e29eda82885bc255362072840e9642

**Comment by progval** [comment]
Thanks! swh-graph compiles with the latest `havoc` now

**Comment by vigna** [comment]
So, we played a little bit and it looks like the problem is that we should have a chain of dependency on lifetimes in the trait: the graph should outlive the iterator which should outlive the successors. This is not the case at the moment, and that causes the problem with returning an iterator that depends on a parameter related internal state of the graph, even if we actually clone that.

**Comment by vigna** [comment]
Ok, I was totally fooled by the parameter syntax.  I now realize that ArcListGraph works perfectly in transpose.rs:
```rust
    // transpose the graph
    let sorted = webgraph::algorithms::transpose(&seq_graph, args.batch_size).unwrap();
    // compress the transposed graph
    parallel_compress_sequential_iter::<
        arc_list_graph::NodeIterator<std::iter::Map<KMergeIters<_>, _>>,
    >(
        args.basename,
        &mut sorted.iter(),
        sorted.num_nodes(),
        compression_flags,
        args.num_cpus.unwrap_or(rayon::current_num_threads()),
    )
    .unwrap();
```
Here `sorted` is an `ArcListGraph`. `'static` means that the iterator cannot contain references, but everything here is owned.

I don't really understand why `ArcListGraph` should be just useful for toy examples. You have just to provide an iterator on pairs that is entirely owned, but that doesn't seem to be so dramatic.

**Comment by progval** [comment]
> You have just to provide an iterator on pairs that is entirely owned, but that doesn't seem to be so dramatic.

True.

In my case, the iterator was a `Map<_, F>` where `F` is a function that borrows something else (the MPHF and the ProgressLogger). I could work around with an `Arc` but that's inconvenient.

Anyway, NodeIterator works just fine for my use case.

**Comment by vigna** [comment]
A nice effect of making labels work is that 'static is no longer necessary. The new implied-bound propagation mechanism seems to be taking care of that.
